from pynput import keyboard

#Ele recebe uma chave em config.json, e retorna um valor em BloodForce.py, a tecla será usada para iniciar o "bf_start()":
key_dic = {
    'f1' : keyboard.Key.f1,
    'f2' : keyboard.Key.f2,
    'f3' : keyboard.Key.f3,
    'f4' : keyboard.Key.f4,
    'f5' : keyboard.Key.f5,
    'f6' : keyboard.Key.f6,
    'f7' : keyboard.Key.f7,
    'f8' : keyboard.Key.f8,
    'f9' : keyboard.Key.f9,
    'f10' : keyboard.Key.f10,
    'f11' : keyboard.Key.f11,
    'f12' : keyboard.Key.f12,
    'esc' : keyboard.Key.esc,
    'alt' : keyboard.Key.alt,
    'alt_gr' : keyboard.Key.alt_gr,
    'caps_lock' : keyboard.Key.caps_lock,
    'backspace' : keyboard.Key.backspace,
    'ctrl' : keyboard.Key.ctrl,
    'shift' : keyboard.Key.shift,
    'delete' : keyboard.Key.delete,
    'down' : keyboard.Key.down,
    'enter' : keyboard.Key.enter,
    'end' : keyboard.Key.end,
    'home' : keyboard.Key.home,
    'insert' : keyboard.Key.insert,
    'left' : keyboard.Key.left,
    'page_down' : keyboard.Key.page_down,
    'page_up' : keyboard.Key.page_up,
    'scroll_lock' : keyboard.Key.scroll_lock,
    'right' : keyboard.Key.right,
    'print_screen' : keyboard.Key.print_screen,
    'up' : keyboard.Key.up,
    'space' : keyboard.Key.space,
    'tab' : keyboard.Key.tab
        }